Add java 11 explicit dependencies Explicitly include java.xml.bind.jaxb-api and javax.activation
Summary:
=======
Java 11 has removed some modules, we need to explicitly add them to the classpath.

Without these modules, NoClassDefFoundError exceptions will fire.
These exceptions appear to be caught, but we can avoid them altogether by adding the dependencies explicitly.

Actions:
=======
* Include javax.xml.bind.jaxb-api 2.3.1 as a dependency.
* Include javax.activation.activation 1.1.1 as a dependency.